// web/src/lib/components/Sidebar.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ArrowUpToLine, PanelLeftClose, PanelLeftOpen, File } from 'lucide-svelte';
  import FileUploader from '$lib/components/UploadFile.svelte';
  import { endpointMapping } from "$lib/utils/constants";

  let isExpanded = true;
  let files: Record<string, any> = {};
  let error: string | null = null;

  const toggleSidebar = () => {
    isExpanded = !isExpanded;
  };

  const handleFileClick = (fileName: string, metadata: any) => {
    // Implementation depends on your routing/store solution in Svelte
    console.log(`File clicked: ${fileName}`, metadata);
    // You might want to use Svelte's stores to save metadata
    // And use svelte-navigator or other routing solution to navigate
  };

  const fetchFiles = async () => {
    try {
      const response = await fetch(endpointMapping.getStaticFireMetadataUrl);
      if (!response.ok) throw new Error("Failed to fetch files");
      files = await response.json();
      error = null;
    } catch (err) {
      error = err instanceof Error ? err.message : "An error occurred.";
    }
  };

  onMount(() => {
    fetchFiles();
  });

  const handleUploadComplete = () => {
    // Refetch the files after upload completes
    fetchFiles();
  };
</script>

<aside class="side-bar {isExpanded ? 'expanded' : 'collapsed'}">
  <!-- Upload Section -->
  <div class="upload-container">
    <FileUploader onUploadComplete={handleUploadComplete} />
  </div>

  <!-- Files Header -->
  <div class="files-header">
    {#if isExpanded}
      <h3>Files</h3>
    {/if}
    <button class="layout-button" on:click={toggleSidebar}>
      {#if isExpanded}
        <PanelLeftClose size={20} />
      {:else}
        <PanelLeftOpen size={20} />
      {/if}
    </button>
  </div>

  <!-- File List -->
  <div class="file-list">
    {#if Object.keys(files).length > 0}
      {#each Object.entries(files) as [name, metadata]}
        <button 
          class="file-item" 
          on:click={() => handleFileClick(name, metadata)}
        >
          <File size={16} class="icon" />
          {#if isExpanded}
            <span class="file-name">{name.replace(/\.[^.]+$/, "")}</span>
          {/if}
        </button>
      {/each}
    {:else}
      <p class="empty">{error || "No uploaded files yet."}</p>
    {/if}
  </div>
</aside>

<style lang="scss">
  @use "../styles/variables.scss" as *;

  .side-bar {
    display: flex;
    flex-direction: column;
    background-color: #121212;
    box-shadow: 2px 0 10px rgba(0, 0, 0, 0.3);
    transition: width 0.3s ease;
    height: 100vh;
    overflow: hidden;
    border-right: 1px solid $outline-color-1;

    &.expanded {
      width: 280px;
    }

    &.collapsed {
      width: 60px;
    }
  }

  .upload-container {
    width: 16rem;
    padding: 1rem;
    display: flex;
    justify-content: center;

  }

  .files-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 0.75rem 1rem;

    h3 {
      font-size: 1.25rem;
      font-weight: 600;
      color: white;
    }

    .layout-button {
      background: transparent;
      border: none;
      color: white;
      padding: 0.25rem;
      cursor: pointer;
      display: flex;
      align-items: center;
      justify-content: center;
    }
  }

  .file-list {
    flex: 1;
    overflow-y: auto;
    padding: 0 0.5rem;
    display: flex;
    flex-direction: column;
  }

  .file-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    color: white;
    padding: 0.5rem;
    border-radius: 4px;
    border: none;
    background: transparent;
    cursor: pointer;

    &:hover {
      background-color: rgba(255, 255, 255, 0.1);
    }

    .file-name {
      font-size: 0.9rem;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }
  }

  .empty {
    color: #aaa;
    font-size: 0.9rem;
    padding: 1rem;
  }
</style>

// Frontend/components/sidebar.tsx
"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { useMetadataStore } from "../stores/metadataStore";
import { endpointMapping } from "@/utils/constants";
import { File, PanelLeftClose, PanelLeftOpen, Upload } from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import FileUploader from "@/components/FileUploader";

export function Sidebar() {
  const router = useRouter();
  const [isCollapsed, setIsCollapsed] = React.useState(false);
  const [files, setFiles] = React.useState<Record<string, any>>({});
  const [error, setError] = React.useState<string | null>(null);
  const setMetadata = useMetadataStore((state) => state.setMetadata);

  React.useEffect(() => {
    const fetchFiles = async () => {
      try {
        const response = await fetch(endpointMapping.getStaticFireMetadataUrl);
        if (!response.ok) throw new Error("Failed to fetch files");
        const data = await response.json();
        setFiles(data);
        setError(null);
      } catch (err) {
        setError((err as Error).message || "An error occurred.");
      }
    };
    fetchFiles();
  }, []);

  // Handle file selection and navigate to Dashboard
  const handleFileClick = (name: string, metadata: any) => {
    // Set metadata in store
    setMetadata(metadata, metadata.xColumnNames[0], metadata.yColumnNames[0], name);
    
    // Navigate to Dashboard with fileId
    router.push(`/dashboard/${encodeURIComponent(name)}`);
  };

  return (
    <div className={cn("h-[calc(100vh-3.5rem)] border-r bg-background transition-all duration-300", isCollapsed ? "w-[60px]" : "w-[280px]")}>
      
      {/* Upload Section */}
      {isCollapsed ? (
        <div className="p-4 flex items-center justify-center">
          <Button variant="ghost" size="icon">
            <Upload className="h-5 w-5" />
          </Button>
        </div>
      ) : (
        <div className="p-4">
          <FileUploader />
        </div>
      )}

      {/* Sidebar Header */}
      <div className="p-4 flex justify-between items-center">
        <h2 className={cn("font-semibold", isCollapsed && "hidden")}>Files</h2>
        <Button variant="ghost" size="icon" onClick={() => setIsCollapsed(!isCollapsed)}>
          {isCollapsed ? <PanelLeftOpen className="h-4 w-4" /> : <PanelLeftClose className="h-4 w-4" />}
        </Button>
      </div>

      {/* File List */}
      <div className="overflow-auto h-[calc(100vh-7.5rem)]">
        {Object.keys(files).length > 0 ? (
          Object.entries(files).map(([name, metadata]) => (
            <Button
              key={name}
              variant="ghost"
              className="w-full justify-start p-2 mb-1 hover:bg-accent hover:text-accent-foreground"
              onClick={() => handleFileClick(name, metadata)}
            >
              <File className="h-4 w-4 mr-2" />
              {!isCollapsed && <span>{name.replace(/\.[^.]+$/, "")}</span>}
            </Button>
          ))
        ) : (
          <p className="p-4 text-sm text-muted-foreground">{error || "No uploaded files yet."}</p>
        )}
      </div>
    </div>
  );
}
